steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/737-2023-t1-prac5p:$COMMIT_SHA', '.']


# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/737-2023-t1-prac5p:$COMMIT_SHA']


- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/prac10d', 'prac10d=gcr.io/${PROJECT_ID}/737-2023-t1-prac5p:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'