version: '3.9'
services:
  app:
    build: .
    image: pauljose97/737-2023-t1-prac5p
    container_name: 737-2023-t1-prac5p
    ports:
      - "8080:3030"
    volumes:
      - ./src:/app/src
    healthcheck:
      test: curl --fail http://localhost:3030 || exit 1
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s